# Generated by Django 4.2.20 on 2025-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', '充值'), ('withdraw', '提现'), ('answer_income', '回答收入'), ('course_purchase', '购买课程'), ('course_income', '课程收入'), ('question_reply', '问题支出'), ('other_income', '其它收入')], max_length=20),
        ),
    ]
