# Generated by Django 4.2.20 on 2025-03-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=32, verbose_name='居住地'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(default=None, max_length=16, verbose_name='所在行业'),
            preserve_default=False,
        ),
    ]
