# Generated by Django 4.2.20 on 2025-03-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他'), ('N', '保密')], default='N', max_length=1, verbose_name='性别'),
        ),
    ]
