# Generated by Django 4.2.20 on 2025-03-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('open', '开放中'), ('closed', '审核中'), ('answered', '已回答')], default='open', max_length=10),
        ),
    ]
