# Generated by Django 4.2.20 on 2025-04-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核未通过')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('open', '开放中'), ('closed', '审核中'), ('false', '审核失败'), ('answered', '已回答')], default='closed', max_length=10),
        ),
    ]
