# Generated by Django 4.2.20 on 2025-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_answer_updated_at_answer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('open', '开放中'), ('closed', '关闭显示'), ('pending', '审核中'), ('false', '审核失败'), ('answered', '已回答')], default='pending', max_length=10),
        ),
    ]
