# Generated by Django 4.2.20 on 2025-04-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核未通过'), ('user_approved', '用户接受'), ('user_rejected', '用户拒绝')], default='pending', max_length=20),
        ),
    ]
