# Generated by Django 4.2.20 on 2025-04-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('open', '开放'), ('closed', '关闭')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
    ]
